print('====TABUADA====')
num = int(input('Digite um número: '))
print(f'A tabuada do número {num} é: ')
print(f'{num * 1}')
print(f'{num * 2}')
print(f'{num * 3}')
print(f'{num * 4}')
print(f'{num * 5}')
print(f'{num * 6}')
print(f'{num * 7}')
print(f'{num * 8}')
print(f'{num * 9}')
print(f'{num * 10}')